local HUD_EDITOR_BOOT_DOCUMENT = {
    version = 1,
    revision = 0,
    id = "hc_controller_layout",
    name = "HC Controller Layout",
    selectedId = "main_canvas",
    screenWidth = 1920,
    screenHeight = 1080,
    elements = {
        {
            id = "frame",
            type = "boxRounded",
            visible = true,
            x = 32, y = 36, w = 1848, h = 1006, radius = 22,
            fill = { 0.10, 0.11, 0.12, 0.98 },
            stroke = { 0.97, 0.97, 0.98, 1.00 },
            strokeWidth = 4,
            textLines = {},
            textColor = { 1, 1, 1, 1 },
            textSize = 18,
            textAlign = "center",
            rotation = 0,
            shadowBlur = 0,
            shadowColor = { 0, 0, 0, 0 },
            imageSrc = "",
            imageFit = "contain",
            quadInset = 0.125,
        },
        {
            id = "title_badge",
            type = "boxRounded",
            visible = true,
            x = 64, y = 48, w = 280, h = 98, radius = 18,
            fill = { 0.16, 0.16, 0.16, 0.96 },
            stroke = { 0.98, 0.98, 0.99, 1.00 },
            strokeWidth = 4,
            textLines = { "Honeycomb Control" },
            textColor = { 1.00, 0.73, 0.24, 1.00 },
            textSize = 32,
            textAlign = "center",
            rotation = 0,
            shadowBlur = 0,
            shadowColor = { 0, 0, 0, 0 },
            imageSrc = "",
            imageFit = "contain",
            quadInset = 0.125,
        },
        {
            id = "purity_panel",
            type = "boxRounded",
            visible = true,
            x = 78, y = 168, w = 160, h = 162, radius = 18,
            fill = { 0.23, 0.16, 0.05, 0.96 },
            stroke = { 0.98, 0.86, 0.45, 1.00 },
            strokeWidth = 3,
            textLines = { "Pure", "Product", "74t/s" },
            textColor = { 1.00, 0.91, 0.56, 1.00 },
            textSize = 26,
            textAlign = "center",
            rotation = 0,
            shadowBlur = 0,
            shadowColor = { 0, 0, 0, 0 },
            imageSrc = "",
            imageFit = "contain",
            quadInset = 0.125,
        },
        {
            id = "materials_strip",
            type = "boxRounded",
            visible = true,
            x = 390, y = 48, w = 1410, h = 136, radius = 18,
            fill = { 0.19, 0.20, 0.22, 0.96 },
            stroke = { 0.96, 0.96, 0.98, 1.00 },
            strokeWidth = 4,
            textLines = {},
            textColor = { 1, 1, 1, 1 },
            textSize = 18,
            textAlign = "center",
            rotation = 0,
            shadowBlur = 0,
            shadowColor = { 0, 0, 0, 0 },
            imageSrc = "",
            imageFit = "contain",
            quadInset = 0.125,
        },
        {
            id = "tier_all",
            type = "boxRounded",
            visible = true,
            x = 440, y = 58, w = 86, h = 40, radius = 18,
            fill = { 0.98, 0.78, 0.13, 0.98 },
            stroke = { 0.90, 0.63, 0.05, 1.00 },
            strokeWidth = 2,
            textLines = { "All" },
            textColor = { 0.22, 0.15, 0.02, 1.00 },
            textSize = 22,
            textAlign = "center",
            rotation = 0,
            shadowBlur = 0,
            shadowColor = { 0, 0, 0, 0 },
            imageSrc = "",
            imageFit = "contain",
            quadInset = 0.125,
        },
        {
            id = "tier_l1",
            type = "boxRounded",
            visible = true,
            x = 544, y = 58, w = 106, h = 40, radius = 18,
            fill = { 0.95, 0.66, 0.16, 0.98 },
            stroke = { 0.90, 0.54, 0.04, 1.00 },
            strokeWidth = 2,
            textLines = { "L1 T1" },
            textColor = { 0.24, 0.12, 0.02, 1.00 },
            textSize = 20,
            textAlign = "center",
            rotation = 0,
            shadowBlur = 0,
            shadowColor = { 0, 0, 0, 0 },
            imageSrc = "",
            imageFit = "contain",
            quadInset = 0.125,
        },
        {
            id = "tier_l2",
            type = "boxRounded",
            visible = true,
            x = 668, y = 58, w = 106, h = 40, radius = 18,
            fill = { 0.95, 0.66, 0.16, 0.98 },
            stroke = { 0.90, 0.54, 0.04, 1.00 },
            strokeWidth = 2,
            textLines = { "L2 T2" },
            textColor = { 0.24, 0.12, 0.02, 1.00 },
            textSize = 20,
            textAlign = "center",
            rotation = 0,
            shadowBlur = 0,
            shadowColor = { 0, 0, 0, 0 },
            imageSrc = "",
            imageFit = "contain",
            quadInset = 0.125,
        },
        {
            id = "tier_l3",
            type = "boxRounded",
            visible = true,
            x = 792, y = 58, w = 106, h = 40, radius = 18,
            fill = { 0.95, 0.66, 0.16, 0.98 },
            stroke = { 0.90, 0.54, 0.04, 1.00 },
            strokeWidth = 2,
            textLines = { "L3 T3" },
            textColor = { 0.24, 0.12, 0.02, 1.00 },
            textSize = 20,
            textAlign = "center",
            rotation = 0,
            shadowBlur = 0,
            shadowColor = { 0, 0, 0, 0 },
            imageSrc = "",
            imageFit = "contain",
            quadInset = 0.125,
        },
        {
            id = "tier_l4",
            type = "boxRounded",
            visible = true,
            x = 916, y = 58, w = 106, h = 40, radius = 18,
            fill = { 0.95, 0.66, 0.16, 0.98 },
            stroke = { 0.90, 0.54, 0.04, 1.00 },
            strokeWidth = 2,
            textLines = { "L4 T4" },
            textColor = { 0.24, 0.12, 0.02, 1.00 },
            textSize = 20,
            textAlign = "center",
            rotation = 0,
            shadowBlur = 0,
            shadowColor = { 0, 0, 0, 0 },
            imageSrc = "",
            imageFit = "contain",
            quadInset = 0.125,
        },
        {
            id = "materials_band",
            type = "boxRounded",
            visible = true,
            x = 440, y = 108, w = 1320, h = 70, radius = 14,
            fill = { 0.15, 0.21, 0.31, 0.96 },
            stroke = { 0.70, 0.91, 1.00, 1.00 },
            strokeWidth = 2,
            textLines = { "Aluminum   Carbon   Iron   Silicon   Calcium   Chromium   Copper   Sodium" },
            textColor = { 0.78, 0.95, 1.00, 1.00 },
            textSize = 20,
            textAlign = "center",
            rotation = 0,
            shadowBlur = 0,
            shadowColor = { 0, 0, 0, 0 },
            imageSrc = "",
            imageFit = "contain",
            quadInset = 0.125,
        },
        {
            id = "preview_panel",
            type = "boxRounded",
            visible = true,
            x = 78, y = 214, w = 228, h = 266, radius = 18,
            fill = { 0.14, 0.14, 0.15, 0.98 },
            stroke = { 0.97, 0.97, 0.98, 1.00 },
            strokeWidth = 4,
            textLines = {},
            textColor = { 1, 1, 1, 1 },
            textSize = 18,
            textAlign = "center",
            rotation = 0,
            shadowBlur = 0,
            shadowColor = { 0, 0, 0, 0 },
            imageSrc = "",
            imageFit = "contain",
            quadInset = 0.125,
        },
        {
            id = "status_badge",
            type = "boxRounded",
            visible = true,
            x = 92, y = 526, w = 168, h = 62, radius = 28,
            fill = { 0.78, 0.06, 0.10, 0.96 },
            stroke = { 0.99, 0.99, 0.99, 1.00 },
            strokeWidth = 2,
            textLines = { "Stopped" },
            textColor = { 1.00, 0.68, 0.26, 1.00 },
            textSize = 28,
            textAlign = "center",
            rotation = 0,
            shadowBlur = 0,
            shadowColor = { 0, 0, 0, 0 },
            imageSrc = "",
            imageFit = "contain",
            quadInset = 0.125,
        },
        {
            id = "actions_panel",
            type = "boxRounded",
            visible = true,
            x = 64, y = 608, w = 268, h = 344, radius = 18,
            fill = { 0.18, 0.18, 0.18, 0.98 },
            stroke = { 0.97, 0.97, 0.98, 1.00 },
            strokeWidth = 4,
            textLines = { "M0", "Maintain x100" },
            textColor = { 1.00, 0.72, 0.24, 1.00 },
            textSize = 28,
            textAlign = "center",
            rotation = 0,
            shadowBlur = 0,
            shadowColor = { 0, 0, 0, 0 },
            imageSrc = "",
            imageFit = "contain",
            quadInset = 0.125,
        },
        {
            id = "button_maintain",
            type = "boxRounded",
            visible = true,
            x = 96, y = 734, w = 204, h = 58, radius = 22,
            fill = { 0.18, 0.74, 0.96, 0.98 },
            stroke = { 0.86, 0.97, 1.00, 1.00 },
            strokeWidth = 2,
            textLines = { "Maintain 1" },
            textColor = { 0.07, 0.22, 0.31, 1.00 },
            textSize = 22,
            textAlign = "center",
            rotation = 0,
            shadowBlur = 0,
            shadowColor = { 0, 0, 0, 0 },
            imageSrc = "",
            imageFit = "contain",
            quadInset = 0.125,
        },
        {
            id = "button_craft",
            type = "boxRounded",
            visible = true,
            x = 96, y = 806, w = 204, h = 58, radius = 22,
            fill = { 0.18, 0.74, 0.96, 0.98 },
            stroke = { 0.86, 0.97, 1.00, 1.00 },
            strokeWidth = 2,
            textLines = { "Craft 1" },
            textColor = { 0.07, 0.22, 0.31, 1.00 },
            textSize = 22,
            textAlign = "center",
            rotation = 0,
            shadowBlur = 0,
            shadowColor = { 0, 0, 0, 0 },
            imageSrc = "",
            imageFit = "contain",
            quadInset = 0.125,
        },
        {
            id = "button_stop",
            type = "boxRounded",
            visible = true,
            x = 96, y = 878, w = 204, h = 58, radius = 22,
            fill = { 0.95, 0.48, 0.18, 0.98 },
            stroke = { 1.00, 0.87, 0.63, 1.00 },
            strokeWidth = 2,
            textLines = { "Stop" },
            textColor = { 0.33, 0.12, 0.02, 1.00 },
            textSize = 24,
            textAlign = "center",
            rotation = 0,
            shadowBlur = 0,
            shadowColor = { 0, 0, 0, 0 },
            imageSrc = "",
            imageFit = "contain",
            quadInset = 0.125,
        },
        {
            id = "main_canvas",
            type = "boxRounded",
            visible = true,
            x = 370, y = 198, w = 1410, h = 768, radius = 20,
            fill = { 0.15, 0.15, 0.15, 0.98 },
            stroke = { 0.97, 0.97, 0.98, 1.00 },
            strokeWidth = 4,
            textLines = { "No schematic required", "Nothing selected" },
            textColor = { 0.98, 0.66, 0.19, 1.00 },
            textSize = 24,
            textAlign = "center",
            rotation = 0,
            shadowBlur = 0,
            shadowColor = { 0, 0, 0, 0 },
            imageSrc = "",
            imageFit = "contain",
            quadInset = 0.125,
        },
        {
            id = "footer_status",
            type = "boxRounded",
            visible = true,
            x = 1060, y = 988, w = 86, h = 34, radius = 14,
            fill = { 0.12, 0.80, 0.96, 0.98 },
            stroke = { 0.88, 0.98, 1.00, 1.00 },
            strokeWidth = 2,
            textLines = {},
            textColor = { 1, 1, 1, 1 },
            textSize = 18,
            textAlign = "center",
            rotation = 0,
            shadowBlur = 0,
            shadowColor = { 0, 0, 0, 0 },
            imageSrc = "",
            imageFit = "contain",
            quadInset = 0.125,
        },
    }
}

return HUD_EDITOR_BOOT_DOCUMENT
